---
- hosts: localhost
  gather_facts: False
  become: yes
  tasks:
  # Section Add Indice
  - name: Create indice test
    elasticsearch:
      url: 'http://myelasticsearch.fr:9200'
      type: indice
      indice_name: test
      state: present
  - name: Create indice test
    elasticsearch:
      url: 'http://myelasticsearch.fr:9200'
      type: indice
      indice_name: test
      state: present
  - name: Create indice test2
    elasticsearch:
      url: 'http://myelasticsearch.fr:9200'
      type: indice
      indice_name: test2
      state: present


  # Section Add Document
  - name: Add a document in indice test
    elasticsearch:
      url: 'http://myelasticsearch.fr:9200'
      type: document
      indice_name: test
      mapping_type: doc
      document:
        user: "kimchy"
        post_date: "2009-11-15T14:12:12"
        message: "trying out Elasticsearch"
  - name: Add another document in indice test
    elasticsearch:
      url: 'http://myelasticsearch.fr:9200'
      type: document
      indice_name: test2
      mapping_type: doc
      document: |
        {
          "user": "kimchy",
          "post_date": "2009-11-15T14:12:12",
          "message": "trying out Elasticsearch"
        }


  # Section Rename Indice
  - name: Rename indice test to test2
    elasticsearch:
      url: 'http://myelasticsearch.fr:9200'
      type: indice
      indice_name: test
      rename: test2
      state: rename

  # Section Delete Indice
  - name: Delete indice test
    elasticsearch:
      url: 'http://myelasticsearch.fr:9200'
      type: indice
      indice_name: test
      state: absent
  - name: Delete indice test2
    elasticsearch:
      url: 'http://myelasticsearch.fr:9200'
      type: indice
      indice_name: test2
      state: absent
  - name: Delete indice test
    elasticsearch:
      url: 'http://myelasticsearch.fr:9200'
      type: indice
      indice_name: test
      state: absent


  # Section Errors Handling
  - name: URL does not exist | Throw error
    ignore_errors: True
    elasticsearch:
      url: 'http://blabla.fr'
      type: indice
      indice_name: test
      state: present
  - name: URL does not exist | Throw error
    ignore_errors: True
    elasticsearch:
      url: 'http://myelasticsearch.fr:8888'
      type: indice
      indice_name: test
      state: absent
  - name: Fatal | Create indice | Throw error
    ignore_errors: True
    elasticsearch:
      url: 'http://myelasticsearch.fr:8888'
      type: indice
      indice_name: test
      rename: test2
      state: rename
  - name: Fatal | Add a document  | Throw error
    ignore_errors: True
    elasticsearch:
      url: 'http://badurl.fr:9200'
      type: document
      indice_name: test
      mapping_type: _doc
      document:
        user: "kimchy"
        post_date: "2009-11-15T14:12:12"
        message: "trying out Elasticsearch"
